# Generated by Django 4.0.5 on 2022-06-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_alter_employee_age_alter_employee_create_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='create_time',
            field=models.DateTimeField(verbose_name='入职日期'),
        ),
    ]
