# Generated by Django 4.1 on 2022-11-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_pie_chart_alter_employee_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='bar_chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(max_length=64, verbose_name='星期名')),
                ('direct', models.IntegerField()),
                ('email', models.IntegerField()),
                ('union_ads', models.IntegerField()),
                ('video_ads', models.IntegerField()),
                ('search_engine', models.IntegerField()),
            ],
        ),
    ]
