# Generated by Django 4.1 on 2022-12-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_line_chart_alter_employee_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='line_chart',
            name='time',
            field=models.DateField(verbose_name='时间'),
        ),
    ]
