# Generated by Django 4.1 on 2022-12-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_boss_alter_employee_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boss',
            name='img',
            field=models.FileField(max_length=64, upload_to='', verbose_name='头像'),
        ),
    ]
