# Generated by Django 4.1 on 2023-03-21 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_alter_boss_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='emp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.employee', verbose_name='员工'),
        ),
        migrations.AddField(
            model_name='task',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.admin', verbose_name='管理员'),
        ),
        migrations.AddField(
            model_name='task',
            name='emp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.employee', verbose_name='员工'),
        ),
    ]
