# Generated by Django 4.1 on 2023-03-21 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0016_remove_order_admin_remove_task_user_order_emp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别'),
        ),
    ]
