# Generated by Django 4.1 on 2023-03-21 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0018_alter_employee_gender_alter_order_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='create_time',
            field=models.DateTimeField(default='2023-03-21 00:00:00.000000', verbose_name='支付日期'),
        ),
    ]
