# Generated by Django 4.1 on 2023-03-21 03:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0019_order_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='支付日期'),
        ),
    ]
