# Generated by Django 4.1 on 2023-03-21 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0020_alter_order_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.CharField(default=None, max_length=64, verbose_name='商品分类'),
        ),
    ]
